github:
  - user: R00T-me
    repo: Bloody-Weather
    type: individual

crypto:
  - type: bitcoin
    address: bc1q65fj4esmfapm59x99xgkz7mcp9jl2ee3pgxx3d
    label: "Bitcoin Wallet"
  - type: ethereum
    address: 0x3C2F6Ee719b64DEDF6e834b851123D2e5c0a8f27
    label: "Ethereum Wallet"
  - type: USDT
    address: 0x3C2F6Ee719b64DEDF6e834b851123D2e5c0a8f27
    label: "USDT Wallet"
