# These are supported funding model platforms

github: R00T-me

custom: ['My Public Address to Receive BTC bc1q65fj4esmfapm59x99xgkz7mcp9jl2ee3pgxx3d
', 'My Public Address to Receive ETH 0x3C2F6Ee719b64DEDF6e834b851123D2e5c0a8f27' , 'My Public Address to Receive USDT 0x3C2F6Ee719b64DEDF6e834b851123D2e5c0a8f27','My Public Address to Receive TRX 0x3C2F6Ee719b64DEDF6e834b851123D2e5c0a8f27']
